### ISSUE TITLE
"!permission_all" command not working

### ISSUE THREAD

**Issue by Deeebs** [OfficialWiddin/DeliBot#1]
Whenever i enter the command on my discord server, i get the message,

"The correct Role was not found. Creating now...
Please re-run this command."

Though even after re-running the command, i get the same issue still. I assumed it possibly needed me to create a Moderator / Delibot role so it would then just enable+assign that to everyone (?), but still nothing worked.

**Comment by OfficialWiddin** [comment]
Hmm, I think you forgot to set "**Manage roles** - Members with this permission can create new roles and edit/delete roles lower than this one." on the Bots role? I tried it on my server and if i forgot to set the right permissions it just keeps on saying "Please re-run".
