### ISSUE TITLE
Mewtwo does not exists in raids?

### ISSUE THREAD

**Issue by Hotchop** [OfficialWiddin/DeliBot#13]
There is an error when trying to get pokebattler info on certain pokemon like Mewtwo, stating that "it does not exist in raids"

**Comment by OfficialWiddin** [comment]
I'll post an fix on this in the upcomming days, like monday.

**Comment by Hotchop** [comment]
Glad to hear, thanks for the response. The admins are very happy with the bot, and we are currently making a spanish translation if you are interested in adding it later.
Also, the pokebattler error also seems to extend to the !counters comand for pvp in some pokemon.
