### ISSUE TITLE
Adding gyms with a bot

### ISSUE THREAD

**Issue by PorkDeCube** [OfficialWiddin/DeliBot#6]
having trouble adding gyms with a bot, sending the same message as me, but delibot doesn't reply and the message is still deleted.
I've got 150+ gyms to add and I didn't want to do it by hand

**Comment by OfficialWiddin** [comment]
Delibot has been updated with new commands,

`!create gym "name" lat lon`
`!delete gym "name"`
`!create pokestop "name" lat lon`
`!delete pokestop "name"`

example: `!create gym "the shiny mountain" 75.00 -20.00`

If you have a large amount of gyms in a file, you can send it to me and i'll insert them.
