### ISSUE TITLE
[Question] Merging multiple ex-raid posts into 1

### ISSUE THREAD

**Issue by darkownage** [OfficialWiddin/DeliBot#7]
Hi,

I was wondering if there was an option to have multiple ex-raid posts merge into a single ex-raid post and then just update the people attending? Cause the behaviour now is, each time a person posts the screenshot a post is made with all the details (which I completely understand from the point of view of the bot) but it would be incredibly helpful if posts about the same (ex)raid could be merged into a single post.

Not sure if this is even doable but just thought I would ask if there was an option for this :)

Thanks in advance!

**Comment by OfficialWiddin** [comment]
Some changes on the recent update:

The image won't be deleted when you post it AND delibot will check if the raid already exists (if it manages to OCR the correct name).
